// lib/generate-claude-md.ts
// Deterministic. Turns a BrandModel into a CLAUDE.md that Claude Code can reference
// as hard constraints. No LLM in the loop — the file is assembled from template + data.

import type { BrandModel } from "./brand-logic";

export function generateClaudeMd(m: BrandModel): string {
  const paletteRows = m.palette
    .map((p) => `| ${p.role} | \`${p.hex}\` | ${p.usage} |`)
    .join("\n");

  const scaleRows = m.typography.scale
    .map((s) => `| ${s.label} | ${s.rem}rem |`)
    .join("\n");

  const chipSection = m.chips.length
    ? m.chips
        .map(
          (c) =>
            `- **${c.id}** — ${c.title}\n  - ${c.detail}`
        )
        .join("\n")
    : "- None. All brand rules resolved deterministically.";

  const iconLinkRows = m.iconStyle.sampleIconLinks
    .map((l) => `- \`${l.name}\` — ${l.url}`)
    .join("\n");

  return `# CLAUDE.md — ${m.brandName} Brand Rules

> Generated by IAS Build 022 (BrandDeck Generator). These are hard brand constraints.
> When generating any UI, copy, or asset for ${m.brandName}, follow these rules exactly.
> Do not invent colors, fonts, or spacing not listed here. If a rule is missing, ask.

## Color palette

Use only these colors. Follow the usage column — do not repurpose a color.

| Role | Hex | Usage |
|------|-----|-------|
${paletteRows}

Distribution: lead with the light canvas, use primary for structure, reserve accent for
a small share of the layout (buttons, links, active states). Color is a splash, not a flood.

## Logo shape & clear space

Shape category: **${m.shape.label}** (${m.shape.aspectRatios})
Typical assets: ${m.shape.exampleAssets}

${m.clearspace.rule}

Minimum clear space: **${m.shape.clearspaceLabel}**.
Nothing — text, imagery, other logos — may enter this margin.

## Typography

- **Display / headings:** ${m.typography.display} (${m.typography.displayUrl})
- **Body / UI text:** ${m.typography.body} (${m.typography.bodyUrl})
- Load both from Google Fonts. Do not substitute system fonts.

Type scale (modular, 1.25 ratio):

| Level | Size |
|-------|------|
${scaleRows}

Rationale: ${m.typography.rationale}

## Iconography

- **Icon set:** ${m.iconStyle.family} (${m.iconStyle.sourceUrl})
- **Style:** ${m.iconStyle.rounding}, fill ${m.iconStyle.fill}, weight ${m.iconStyle.weight}
- Use one icon family everywhere. Do not mix icon styles.

Sample icons (each links to its Google Icons page in your style):

${iconLinkRows}

## Buttons

- **Shape:** ${m.buttonStyle.shape}
- **Border radius:** ${m.buttonStyle.radiusPx === 999 ? "9999px (pill)" : m.buttonStyle.radiusPx + "px"}
- Every button uses this radius. No exceptions.

## Open items (honest gaps)

${chipSection}

---

## How to use this file

1. Place this file at the root of your project as \`CLAUDE.md\`.
2. Claude Code reads it automatically at session start and treats it as project context.
3. When you ask Claude Code to build a page, component, or asset, it will apply these
   brand rules without being reminded.
4. To use as a **Skill** instead: create \`.claude/skills/${slug(m.brandName)}-brand/SKILL.md\`
   and paste this content under a skill front-matter block.

_Generated deterministically. No values were invented — every rule traces to your inputs._
`;
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
